version: '3.8'
services:
  design:
    image: sireeshayanamala93/design:latest
    ports:
      - "81:80"
    deploy:
      relicas: 3
  branding:
    image: sireeshayanamala93/branding:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  consultation:
    image: sireeshayanamala93/consultation:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  promises:
    image: sireeshayanamala93/promises:latest
    ports:
      -p "84:80"
    deploy:
      replicas: 3
