version: '3.8'
services:
  movies:
    image: sireesha943/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: sireesha943/paytmtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: sireesha943/paytmdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: sireesha943/paytmrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
